### PR TITLE
Publication announcements

### PR DESCRIPTION
**Pull request by NeoMokono**
Updating posts/public announcements for papers published in July

### CODE REVIEW

**Comment by NeoMokono** [comment]
Made a few updates to the posts

**Comment by NeoMokono** [comment]
Adding a publication image to the repo

**Comment by NeoMokono** [comment]
@vukosim Please check this PR and let me know of any changes that I need to make

**Comment by vukosim** [comment]
You are doing a merge on the wrong repo 😱

**Pull request closed without merging**
